/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSultanCoreRouteImport } from './routes/api/sultan-core'
import { Route as ApiReconstructionRouteImport } from './routes/api/reconstruction'
import { Route as ApiEstablishSessionRouteImport } from './routes/api/establish-session'
import { Route as ApiPublicSidraMaskRouteImport } from './routes/api/public/sidra-mask'
import { Route as ApiPaymentsCompleteRouteImport } from './routes/api/payments/complete'
import { Route as ApiPaymentsApproveRouteImport } from './routes/api/payments/approve'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSultanCoreRoute = ApiSultanCoreRouteImport.update({
  id: '/api/sultan-core',
  path: '/api/sultan-core',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReconstructionRoute = ApiReconstructionRouteImport.update({
  id: '/api/reconstruction',
  path: '/api/reconstruction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEstablishSessionRoute = ApiEstablishSessionRouteImport.update({
  id: '/api/establish-session',
  path: '/api/establish-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSidraMaskRoute = ApiPublicSidraMaskRouteImport.update({
  id: '/api/public/sidra-mask',
  path: '/api/public/sidra-mask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCompleteRoute = ApiPaymentsCompleteRouteImport.update({
  id: '/api/payments/complete',
  path: '/api/payments/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsApproveRoute = ApiPaymentsApproveRouteImport.update({
  id: '/api/payments/approve',
  path: '/api/payments/approve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/establish-session': typeof ApiEstablishSessionRoute
  '/api/reconstruction': typeof ApiReconstructionRoute
  '/api/sultan-core': typeof ApiSultanCoreRoute
  '/api/payments/approve': typeof ApiPaymentsApproveRoute
  '/api/payments/complete': typeof ApiPaymentsCompleteRoute
  '/api/public/sidra-mask': typeof ApiPublicSidraMaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/establish-session': typeof ApiEstablishSessionRoute
  '/api/reconstruction': typeof ApiReconstructionRoute
  '/api/sultan-core': typeof ApiSultanCoreRoute
  '/api/payments/approve': typeof ApiPaymentsApproveRoute
  '/api/payments/complete': typeof ApiPaymentsCompleteRoute
  '/api/public/sidra-mask': typeof ApiPublicSidraMaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/establish-session': typeof ApiEstablishSessionRoute
  '/api/reconstruction': typeof ApiReconstructionRoute
  '/api/sultan-core': typeof ApiSultanCoreRoute
  '/api/payments/approve': typeof ApiPaymentsApproveRoute
  '/api/payments/complete': typeof ApiPaymentsCompleteRoute
  '/api/public/sidra-mask': typeof ApiPublicSidraMaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/api/establish-session'
    | '/api/reconstruction'
    | '/api/sultan-core'
    | '/api/payments/approve'
    | '/api/payments/complete'
    | '/api/public/sidra-mask'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/api/establish-session'
    | '/api/reconstruction'
    | '/api/sultan-core'
    | '/api/payments/approve'
    | '/api/payments/complete'
    | '/api/public/sidra-mask'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/api/establish-session'
    | '/api/reconstruction'
    | '/api/sultan-core'
    | '/api/payments/approve'
    | '/api/payments/complete'
    | '/api/public/sidra-mask'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiEstablishSessionRoute: typeof ApiEstablishSessionRoute
  ApiReconstructionRoute: typeof ApiReconstructionRoute
  ApiSultanCoreRoute: typeof ApiSultanCoreRoute
  ApiPaymentsApproveRoute: typeof ApiPaymentsApproveRoute
  ApiPaymentsCompleteRoute: typeof ApiPaymentsCompleteRoute
  ApiPublicSidraMaskRoute: typeof ApiPublicSidraMaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sultan-core': {
      id: '/api/sultan-core'
      path: '/api/sultan-core'
      fullPath: '/api/sultan-core'
      preLoaderRoute: typeof ApiSultanCoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reconstruction': {
      id: '/api/reconstruction'
      path: '/api/reconstruction'
      fullPath: '/api/reconstruction'
      preLoaderRoute: typeof ApiReconstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/establish-session': {
      id: '/api/establish-session'
      path: '/api/establish-session'
      fullPath: '/api/establish-session'
      preLoaderRoute: typeof ApiEstablishSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sidra-mask': {
      id: '/api/public/sidra-mask'
      path: '/api/public/sidra-mask'
      fullPath: '/api/public/sidra-mask'
      preLoaderRoute: typeof ApiPublicSidraMaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/complete': {
      id: '/api/payments/complete'
      path: '/api/payments/complete'
      fullPath: '/api/payments/complete'
      preLoaderRoute: typeof ApiPaymentsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/approve': {
      id: '/api/payments/approve'
      path: '/api/payments/approve'
      fullPath: '/api/payments/approve'
      preLoaderRoute: typeof ApiPaymentsApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiEstablishSessionRoute: ApiEstablishSessionRoute,
  ApiReconstructionRoute: ApiReconstructionRoute,
  ApiSultanCoreRoute: ApiSultanCoreRoute,
  ApiPaymentsApproveRoute: ApiPaymentsApproveRoute,
  ApiPaymentsCompleteRoute: ApiPaymentsCompleteRoute,
  ApiPublicSidraMaskRoute: ApiPublicSidraMaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
